# Generated by Django 5.0 on 2023-12-22 08:06

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(db_index=True, max_length=20, verbose_name='price')),
                ('rent_price', models.FloatField(db_index=True, max_length=20, verbose_name='price of rent')),
                ('main_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='main image')),
                ('sub_image1', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='sub image1')),
                ('sub_image2', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='sub image2')),
                ('sub_image3', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='sub image3')),
                ('sub_image4', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='sub image4')),
                ('state', models.CharField(db_index=True, default='State', max_length=30, verbose_name='State')),
                ('address', models.CharField(db_index=True, default='address', max_length=100, verbose_name='Address')),
                ('layout', models.CharField(blank=True, db_index=True, default='bhk', max_length=50, null=True, verbose_name='Layout')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='lastly updated')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.tag')),
            ],
            options={
                'db_table': 'home',
            },
        ),
    ]
