# Generated by Django 5.0 on 2023-12-22 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, default='address', max_length=100, verbose_name='Address')),
                ('sqft', models.CharField(db_index=True, default='sqft', max_length=60, verbose_name='SQFT')),
                ('age_building', models.IntegerField(db_index=True, verbose_name='age of building')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'sellrequest',
            },
        ),
    ]
